# Data Manipulation using Pandas

Author: Andreas Chandra \
[Email](mailto:andreas@jakartaresearch.com) [Github](https://github.com/andreaschandra) [Blog](https://datafolksid.xyz/andreas)

## Contents

Day 2
- Reindexing
- Dropping and Poping
- Numeric Calculation
- String Operation

## Day 2

In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.2.2'

In [42]:
d_data = pd.read_csv("telcom_user_extended_day2.csv")

### Reindexing

DataFrame index plays an important role in some cases such as joining two dataframes \
and re-indexing is needed when we want to change back to ordered number index

slice dataframe with `Partner = Yes`

In [9]:
# YOUR CODE
d_partner = d_data[d_data.Partner == "Yes"].copy()

In [11]:
d_partner

,customer_id,gender,senior_citizen,Partner,Dependents,tenure,phone_service,MultipleLines,InternetService,OnlineSecurity,...,number_of_received_message,minutes_of_call,num_of_call,internet_usage_megabytes,netflix_usage_megabytes,youtube_usage_megabytes,game_usage_megabytes,average_internet_ping,average_internet_speed_in_megabytes,is_married
0,9381-NDKME,Female,1,Yes,No,24,No,No phone service,DSL,No,...,34.0,126.0,14.0,2629.0,976.0,599.0,8.0,15.0,20.425580,No
1,3831-YCPUO,Female,0,Yes,Yes,72,Yes,No,Fiber optic,Yes,...,95.0,70.0,42.0,37258.0,7090.0,5330.0,6664.0,15.0,21.759168,No
2,1506-YJTYT,Male,0,Yes,Yes,45,Yes,Yes,DSL,Yes,...,79.0,168.0,22.0,19331.0,7069.0,6596.0,761.0,15.0,22.123215,No
6,3889-VWBID,Male,0,Yes,Yes,68,Yes,No,DSL,Yes,...,54.0,82.0,26.0,4852.0,9187.0,8473.0,701.0,15.0,22.434314,No
8,7826-VVKWT,Female,1,Yes,Yes,24,Yes,No,Fiber optic,No,...,28.0,139.0,16.0,11755.0,888.0,909.0,6.0,15.0,22.605444,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5966,0754-EEBDC,Male,0,Yes,Yes,4,Yes,No,Wireless,No internet service,...,68.0,165.0,28.0,24759.0,8927.0,7558.0,703.0,298.0,5.490512,No
5967,5322-TEUJK,Female,0,Yes,Yes,71,Yes,Yes,Fiber optic,Yes,...,97.0,32.0,56.0,44314.0,6925.0,8071.0,3660.0,298.0,5.529022,No
5971,7033-CLAMM,Female,0,Yes,Yes,48,Yes,No,Wireless,No internet service,...,66.0,67.0,27.0,6527.0,9369.0,6098.0,583.0,298.0,5.706488,No
5972,7067-KSAZT,Female,1,Yes,No,65,Yes,Yes,Fiber optic,No,...,36.0,283.0,10.0,1537.0,801.0,643.0,3.0,298.0,5.746857,No
5983,4238-JSSWH,Female,1,Yes,No,35,Yes,Yes,Fiber optic,No,...,25.0,122.0,14.0,9380.0,897.0,969.0,6.0,299.0,6.782600,No

In [10]:
d_partner.loc[:5]

,customer_id,gender,senior_citizen,Partner,Dependents,tenure,phone_service,MultipleLines,InternetService,OnlineSecurity,...,number_of_received_message,minutes_of_call,num_of_call,internet_usage_megabytes,netflix_usage_megabytes,youtube_usage_megabytes,game_usage_megabytes,average_internet_ping,average_internet_speed_in_megabytes,is_married
0,9381-NDKME,Female,1,Yes,No,24,No,No phone service,DSL,No,...,34.0,126.0,14.0,2629.0,976.0,599.0,8.0,15.0,20.425580,No
1,3831-YCPUO,Female,0,Yes,Yes,72,Yes,No,Fiber optic,Yes,...,95.0,70.0,42.0,37258.0,7090.0,5330.0,6664.0,15.0,21.759168,No
2,1506-YJTYT,Male,0,Yes,Yes,45,Yes,Yes,DSL,Yes,...,79.0,168.0,22.0,19331.0,7069.0,6596.0,761.0,15.0,22.123215,No

In [15]:
d_partner.iloc[:5, 1:3]

   gender  senior_citizen
0  Female               1
1  Female               0
2    Male               0
6    Male               0
8  Female               1

reset the index using reset_index()

In [16]:
# YOUR CODE
d_partner.reset_index()

,index,customer_id,gender,senior_citizen,Partner,Dependents,tenure,phone_service,MultipleLines,InternetService,...,number_of_received_message,minutes_of_call,num_of_call,internet_usage_megabytes,netflix_usage_megabytes,youtube_usage_megabytes,game_usage_megabytes,average_internet_ping,average_internet_speed_in_megabytes,is_married
0,0,9381-NDKME,Female,1,Yes,No,24,No,No phone service,DSL,...,34.0,126.0,14.0,2629.0,976.0,599.0,8.0,15.0,20.425580,No
1,1,3831-YCPUO,Female,0,Yes,Yes,72,Yes,No,Fiber optic,...,95.0,70.0,42.0,37258.0,7090.0,5330.0,6664.0,15.0,21.759168,No
2,2,1506-YJTYT,Male,0,Yes,Yes,45,Yes,Yes,DSL,...,79.0,168.0,22.0,19331.0,7069.0,6596.0,761.0,15.0,22.123215,No
3,6,3889-VWBID,Male,0,Yes,Yes,68,Yes,No,DSL,...,54.0,82.0,26.0,4852.0,9187.0,8473.0,701.0,15.0,22.434314,No
4,8,7826-VVKWT,Female,1,Yes,Yes,24,Yes,No,Fiber optic,...,28.0,139.0,16.0,11755.0,888.0,909.0,6.0,15.0,22.605444,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,5966,0754-EEBDC,Male,0,Yes,Yes,4,Yes,No,Wireless,...,68.0,165.0,28.0,24759.0,8927.0,7558.0,703.0,298.0,5.490512,No
2894,5967,5322-TEUJK,Female,0,Yes,Yes,71,Yes,Yes,Fiber optic,...,97.0,32.0,56.0,44314.0,6925.0,8071.0,3660.0,298.0,5.529022,No
2895,5971,7033-CLAMM,Female,0,Yes,Yes,48,Yes,No,Wireless,...,66.0,67.0,27.0,6527.0,9369.0,6098.0,583.0,298.0,5.706488,No
2896,5972,7067-KSAZT,Female,1,Yes,No,65,Yes,Yes,Fiber optic,...,36.0,283.0,10.0,1537.0,801.0,643.0,3.0,298.0,5.746857,No
2897,5983,4238-JSSWH,Female,1,Yes,No,35,Yes,Yes,Fiber optic,...,25.0,122.0,14.0,9380.0,897.0,969.0,6.0,299.0,6.782600,No

reset_index() has arguments drop and inplace

In [19]:
# YOUR CODE
d_partner.reset_index(drop=True, inplace=True)

In [20]:
# YOUR CODE
d_partner

,customer_id,gender,senior_citizen,Partner,Dependents,tenure,phone_service,MultipleLines,InternetService,OnlineSecurity,...,number_of_received_message,minutes_of_call,num_of_call,internet_usage_megabytes,netflix_usage_megabytes,youtube_usage_megabytes,game_usage_megabytes,average_internet_ping,average_internet_speed_in_megabytes,is_married
0,9381-NDKME,Female,1,Yes,No,24,No,No phone service,DSL,No,...,34.0,126.0,14.0,2629.0,976.0,599.0,8.0,15.0,20.425580,No
1,3831-YCPUO,Female,0,Yes,Yes,72,Yes,No,Fiber optic,Yes,...,95.0,70.0,42.0,37258.0,7090.0,5330.0,6664.0,15.0,21.759168,No
2,1506-YJTYT,Male,0,Yes,Yes,45,Yes,Yes,DSL,Yes,...,79.0,168.0,22.0,19331.0,7069.0,6596.0,761.0,15.0,22.123215,No
3,3889-VWBID,Male,0,Yes,Yes,68,Yes,No,DSL,Yes,...,54.0,82.0,26.0,4852.0,9187.0,8473.0,701.0,15.0,22.434314,No
4,7826-VVKWT,Female,1,Yes,Yes,24,Yes,No,Fiber optic,No,...,28.0,139.0,16.0,11755.0,888.0,909.0,6.0,15.0,22.605444,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,0754-EEBDC,Male,0,Yes,Yes,4,Yes,No,Wireless,No internet service,...,68.0,165.0,28.0,24759.0,8927.0,7558.0,703.0,298.0,5.490512,No
2894,5322-TEUJK,Female,0,Yes,Yes,71,Yes,Yes,Fiber optic,Yes,...,97.0,32.0,56.0,44314.0,6925.0,8071.0,3660.0,298.0,5.529022,No
2895,7033-CLAMM,Female,0,Yes,Yes,48,Yes,No,Wireless,No internet service,...,66.0,67.0,27.0,6527.0,9369.0,6098.0,583.0,298.0,5.706488,No
2896,7067-KSAZT,Female,1,Yes,No,65,Yes,Yes,Fiber optic,No,...,36.0,283.0,10.0,1537.0,801.0,643.0,3.0,298.0,5.746857,No
2897,4238-JSSWH,Female,1,Yes,No,35,Yes,Yes,Fiber optic,No,...,25.0,122.0,14.0,9380.0,897.0,969.0,6.0,299.0,6.782600,No

### Dropping and Popping

Drop and Pop are often used for removing and moving a column(s)

In [36]:
d_data.columns

Index(['customer_id', 'gender', 'senior_citizen', 'Partner', 'Dependents',
       'tenure', 'phone_service', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'InstallApp', 'email', 'kodepos', 'RecordedDate', 'age',
       'number_of_send_message', 'number_of_received_message',
       'minutes_of_call', 'num_of_call', 'internet_usage_megabytes',
       'netflix_usage_megabytes', 'youtube_usage_megabytes',
       'game_usage_megabytes', 'average_internet_ping',
       'average_internet_speed_in_megabytes', 'is_married'],
      dtype='object')

drop is_married in axis = 1

In [30]:
# YOUR CODE
d_data.drop("is_married", axis=1)

,customer_id,gender,senior_citizen,Partner,Dependents,tenure,phone_service,MultipleLines,InternetService,OnlineSecurity,...,number_of_send_message,number_of_received_message,minutes_of_call,num_of_call,internet_usage_megabytes,netflix_usage_megabytes,youtube_usage_megabytes,game_usage_megabytes,average_internet_ping,average_internet_speed_in_megabytes
0,9381-NDKME,Female,1,Yes,No,24,No,No phone service,DSL,No,...,10.0,34.0,126.0,14.0,2629.0,976.0,599.0,8.0,15.0,20.425580
1,3831-YCPUO,Female,0,Yes,Yes,72,Yes,No,Fiber optic,Yes,...,135.0,95.0,70.0,42.0,37258.0,7090.0,5330.0,6664.0,15.0,21.759168
2,1506-YJTYT,Male,0,Yes,Yes,45,Yes,Yes,DSL,Yes,...,78.0,79.0,168.0,22.0,19331.0,7069.0,6596.0,761.0,15.0,22.123215
3,2272-UOINI,Female,0,No,No,7,Yes,No,DSL,Yes,...,66.0,89.0,166.0,28.0,16221.0,8202.0,6167.0,608.0,15.0,22.169331
4,1641-BYBTK,Male,0,No,Yes,6,Yes,No,Wireless,No internet service,...,66.0,70.0,132.0,22.0,17526.0,9309.0,8484.0,613.0,15.0,22.263776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,8779-QRDMV,Male,1,No,No,1,No,No phone service,DSL,No,...,17.0,38.0,244.0,12.0,3046.0,937.0,777.0,8.0,299.0,6.436184
5982,7663-ZTEGJ,Male,0,No,Yes,29,Yes,Yes,Fiber optic,No,...,41.0,74.0,130.0,20.0,15494.0,7110.0,9321.0,583.0,299.0,6.527040
5983,4238-JSSWH,Female,1,Yes,No,35,Yes,Yes,Fiber optic,No,...,22.0,25.0,122.0,14.0,9380.0,897.0,969.0,6.0,299.0,6.782600
5984,2740-JFBOK,Male,0,No,No,10,Yes,Yes,Wireless,No internet service,...,96.0,177.0,53.0,33.0,45238.0,7397.0,6438.0,2132.0,299.0,7.825139
5985,0835-JKADZ,Female,0,No,No,71,Yes,Yes,Fiber optic,No,...,56.0,70.0,141.0,26.0,19075.0,7667.0,6710.0,714.0,299.0,7.917201

Pop is_married column and save to s_is_married

In [49]:
d_data.columns

Index(['customer_id', 'gender', 'senior_citizen', 'Partner', 'Dependents',
       'tenure', 'phone_service', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'InstallApp', 'email', 'kodepos', 'RecordedDate', 'age',
       'number_of_send_message', 'number_of_received_message',
       'minutes_of_call', 'num_of_call', 'internet_usage_megabytes',
       'netflix_usage_megabytes', 'youtube_usage_megabytes',
       'game_usage_megabytes', 'average_internet_ping',
       'average_internet_speed_in_megabytes', 'is_married'],
      dtype='object')

In [50]:
# YOUR CODE
s_is_married = d_data.pop("is_married")

In [51]:
"is_married" in d_data.columns

False

In [52]:
d_data.columns

Index(['customer_id', 'gender', 'senior_citizen', 'Partner', 'Dependents',
       'tenure', 'phone_service', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'InstallApp', 'email', 'kodepos', 'RecordedDate', 'age',
       'number_of_send_message', 'number_of_received_message',
       'minutes_of_call', 'num_of_call', 'internet_usage_megabytes',
       'netflix_usage_megabytes', 'youtube_usage_megabytes',
       'game_usage_megabytes', 'average_internet_ping',
       'average_internet_speed_in_megabytes'],
      dtype='object')

### Numeric Calculation

In [53]:
d_data.dtypes

customer_id                             object
gender                                  object
senior_citizen                           int64
Partner                                 object
Dependents                              object
tenure                                   int64
phone_service                           object
MultipleLines                           object
InternetService                         object
OnlineSecurity                          object
OnlineBackup                            object
DeviceProtection                        object
TechSupport                             object
StreamingTV                             object
StreamingMovies                         object
Contract                                object
PaperlessBilling                        object
PaymentMethod                           object
MonthlyCharges                         float64
TotalCharges                           float64
Churn                                   object
InstallApp                              object
email                                   object
kodepos                                  int64
RecordedDate                            object
age                                    float64
number_of_send_message                 float64
number_of_received_message             float64
minutes_of_call                        float64
num_of_call                            float64
internet_usage_megabytes               float64
netflix_usage_megabytes                float64
youtube_usage_megabytes                float64
game_usage_megabytes                   float64
average_internet_ping                  float64
average_internet_speed_in_megabytes    float64
dtype: object

Calculate total_usage_internet from internet_usage_megabytes + netflix_usage_megabytes + youtube_usage_megabytes

In [58]:
# YOUR CODE
d_data["total_usage_internet"] = d_data.internet_usage_megabytes + d_data.netflix_usage_megabytes + d_data.youtube_usage_megabytes

In [63]:
d_data.total_usage_internet.mean()

27749.8521550284

In [64]:
d_data.total_usage_internet.median()

26997.0

In [65]:
d_data.total_usage_internet.min()

2155.0

In [67]:
d_data.total_usage_internet.quantile(q=0.25)

16427.5

In [68]:
help(d_data.total_usage_internet)

Help on Series in module pandas.core.series object:

class Series(pandas.core.base.IndexOpsMixin, pandas.core.generic.NDFrame)
 |  Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
 |
 |  One-dimensional ndarray with axis labels (including time series).
 |
 |  Labels need not be unique but must be a hashable type. The object
 |  supports both integer- and label-based indexing and provides a host of
 |  methods for performing operations involving the index. Statistical
 |  methods from ndarray have been overridden to automatically exclude
 |  missing data (currently represented as NaN).
 |
 |  Operations between Series (+, -, /, *, **) align values based on their
 |  associated index values-- they need not be the same length. The result
 |  index will be the sorted union of the two indexes.
 |
 |  Parameters
 |  ----------
 |  data : array-like, Iterable, dict, or scalar value
 |      Contains data stored in Series. If data is a dict, argument order is
 |      maintained.
 |  index : array-like or Index (1d)
 |      Values must be hashable and have the same length as `data`.
 |      Non-unique index values are allowed. Will default to
 |      RangeIndex (0, 1, 2, ..., n) if not provided. If data is dict-like
 |      and index is None, then the keys in the data are used as the index. If the
 |      index is not None, the resulting Series is reindexed with the index values.
 |  dtype : str, numpy.dtype, or ExtensionDtype, optional
 |      Data type for the output Series. If not specified, this will be
 |      inferred from `data`.
 |      See the :ref:`user guide <basics.dtypes>` for more usages.
 |  name : str, optional
 |      The name to give to the Series.
 |  copy : bool, default False
 |      Copy input data.
 |
 |  Examples
 |  --------
 |  Constructing Series from a dictionary with an Index specified
 |
 |  >>> d = {'a': 1, 'b': 2, 'c': 3}
 |  >>> ser = pd.Series(data=d, index=['a', 'b', 'c'])
 |  >>> ser
 |  a   1
 |  b   2
 |  c   3
 |  dtype: int64
 |
 |  The keys of the dictionary match with the Index values, hence the Index
 |  values have no effect.
 |
 |  >>> d = {'a': 1, 'b': 2, 'c': 3}
 |  >>> ser = pd.Series(data=d, index=['x', 'y', 'z'])
 |  >>> ser
 |  x   NaN
 |  y   NaN
 |  z   NaN
 |  dtype: float64
 |
 |  Note that the Index is first build with the keys from the dictionary.
 |  After this the Series is reindexed with the given Index values, hence we
 |  get all NaN as a result.
 |
 |  Method resolution order:
 |      Series
 |      pandas.core.base.IndexOpsMixin
 |      pandas.core.arraylike.OpsMixin
 |      pandas.core.generic.NDFrame
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      pandas.core.base.SelectionMixin
 |      pandas.core.indexing.IndexingMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __array__(self, dtype=None) -> numpy.ndarray
 |      Return the values as a NumPy array.
 |
 |      Users should not call this directly. Rather, it is invoked by
 |      :func:`numpy.array` and :func:`numpy.asarray`.
 |
 |      Parameters
 |      ----------
 |      dtype : str or numpy.dtype, optional
 |          The dtype to use for the resulting NumPy array. By default,
 |          the dtype is inferred from the data.
 |
 |      Returns
 |      -------
 |      numpy.ndarray
 |          The values in the series converted to a :class:`numpy.ndarray`
 |          with the specified `dtype`.
 |
 |      See Also
 |      --------
 |      array : Create a new array from data.
 |      Series.array : Zero-copy view to the array backing the Series.
 |      Series.to_numpy : Series method for similar behavior.
 |
 |      Examples
 |      --------
 |      >>> ser = pd.Series([1, 2, 3])
 |      >>> np.asarray(ser)
 |      array([1, 2, 3])
 |
 |      For timezone-aware data, the timezones may be retained with
 |      ``dtype='object'``
 |
 |      >>> tzser = pd.Series(pd.date_range('2000', periods=2, tz="CET"))
 |      >>> np.asarray(tzser, dtype="object")
 |      array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
 |             Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
 |            dtype=object)
 |
 |      Or the values may be localized to UTC and the tzinfo discarded with
 |      ``dtype='datetime64[ns]'``
 |
 |      >>> np.asarray(tzser, dtype="datetime64[ns]")  # doctest: +ELLIPSIS
 |      array(['1999-12-31T23:00:00.000000000', ...],
 |            dtype='datetime64[ns]')
 |
 |  __float__(self)
 |
 |  __getitem__(self, key)
 |
 |  __hash__(self) -> 'int'
 |      Return hash(self).
 |
 |  __init__(self, data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __int__(self)
 |
 |  __len__(self) -> int
 |      Return the length of the Series.
 |
 |  __long__ = __int__(self)
 |
 |  __matmul__(self, other)
 |      Matrix multiplication using binary `@` operator in Python>=3.5.
 |
 |  __repr__(self) -> str
 |      Return a string representation for a particular Series.
 |
 |  __rmatmul__(self, other)
 |      Matrix multiplication using binary `@` operator in Python>=3.5.
 |
 |  __setitem__(self, key, value)
 |
 |  add(self, other, level=None, fill_value=None, axis=0)
 |      Return Addition of series and other, element-wise (binary operator `add`).
 |
 |      Equivalent to ``series + other``, but with support to substitute a fill_value for
 |      missing data in either one of the inputs.
 |
 |      Parameters
 |      ----------
 |      other : Series or scalar value
 |      fill_value : None or float value, default None (NaN)
 |          Fill existing missing (NaN) values, and any new element needed for
 |          successful Series alignment, with this value before computation.
 |          If data in both corresponding Series locations is missing
 |          the result of filling (at that location) will be missing.
 |      level : int or name
 |          Broadcast across a level, matching Index values on the
 |          passed MultiIndex level.
 |
 |      Returns
 |      -------
 |      Series
 |          The result of the operation.
 |
 |      See Also
 |      --------
 |      Series.radd : Reverse of the Addition operator, see
 |          `Python documentation
 |          <https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types>`_
 |          for more details.
 |
 |      Examples
 |      --------
 |      >>> a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
 |      >>> a
 |      a    1.0
 |      b    1.0
 |      c    1.0
 |      d    NaN
 |      dtype: float64
 |      >>> b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])
 |      >>> b
 |      a    1.0
 |      b    NaN
 |      d    1.0
 |      e    NaN
 |      dtype: float64
 |      >>> a.add(b, fill_value=0)
 |      a    2.0
 |      b    1.0
 |      c    1.0
 |      d    1.0
 |      e    NaN
 |      dtype: float64
 |
 |  agg = aggregate(self, func=None, axis=0, *args, **kwargs)
 |
 |  aggregate(self, func=None, axis=0, *args, **kwargs)
 |      Aggregate using one or more operations over the specified axis.
 |
 |      Parameters
 |      ----------
 |      func : function, str, list or dict
 |          Function to use for aggregating the data. If a function, must either
 |          work when passed a Series or when passed to Series.apply.
 |
 |          Accepted combinations are:
 |
 |          - function
 |          - string function name
 |          - list of functions and/or function names, e.g. ``[np.sum, 'mean']``
 |          - dict of axis labels -> functions, function names or list of such.
 |      axis : {0 or 'index'}
 |              Parameter needed for compatibility with DataFrame.
 |      *args
 |          Positional arguments to pass to `func`.
 |      **kwargs
 |          Keyword arguments to pass to `func`.
 |
 |      Returns
 |      -------
 |      scalar, Series or DataFrame
 |
 |          The return can be:
 |
 |          * scalar : when Series.agg is called with single function
 |          * Series : when DataFrame.agg is called with a single function
 |          * DataFrame : when DataFrame.agg is called with several functions
 |
 |          Return scalar, Series or DataFrame.
 |
 |      See Also
 |      --------
 |      Series.apply : Invoke function on a Series.
 |      Series.transform : Transform function producing a Series with like indexes.
 |
 |      Notes
 |      -----
 |      `agg` is an alias for `aggregate`. Use the alias.
 |
 |      A passed user-defined-function will be passed a Series for evaluation.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series([1, 2, 3, 4])
 |      >>> s
 |      0    1
 |      1    2
 |      2    3
 |      3    4
 |      dtype: int64
 |
 |      >>> s.agg('min')
 |      1
 |
 |      >>> s.agg(['min', 'max'])
 |      min   1
 |      max   4
 |      dtype: int64
 |
 |  align(self, other, join='outer', axis=None, level=None, copy=True, fill_value=None, method=None, limit=None, fill_axis=0, broadcast_axis=None)
 |      Align two objects on their axes with the specified join method.
 |
 |      Join method is specified for each axis Index.
 |
 |      Parameters
 |      ----------
 |      other : DataFrame or Series
 |      join : {'outer', 'inner', 'left', 'right'}, default 'outer'
 |      axis : allowed axis of the other object, default None
 |          Align on index (0), columns (1), or both (None).
 |      level : int or level name, default None
 |          Broadcast across a level, matching Index values on the
 |          passed MultiIndex level.
 |      copy : bool, default True
 |          Always returns new objects. If copy=False and no reindexing is
 |          required then original objects are returned.
 |      fill_value : scalar, default np.NaN
 |          Value to use for missing values. Defaults to NaN, but can be any
 |          "compatible" value.
 |      method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
 |          Method to use for filling holes in reindexed Series:
 |
 |          - pad / ffill: propagate last valid observation forward to next valid.
 |          - backfill / bfill: use NEXT valid observation to fill gap.
 |
 |      limit : int, default None
 |          If method is specified, this is the maximum number of consecutive
 |          NaN values to forward/backward fill. In other words, if there is
 |          a gap with more than this number of consecutive NaNs, it will only
 |          be partially filled. If method is not specified, this is the
 |          maximum number of entries along the entire axis where NaNs will be
 |          filled. Must be greater than 0 if not None.
 |      fill_axis : {0 or 'index'}, default 0
 |          Filling axis, method and limit.
 |      broadcast_axis : {0 or 'index'}, default None
 |          Broadcast values along this axis, if aligning two objects of
 |          different dimensions.
 |
 |      Returns
 |      -------
 |      (left, right) : (Series, type of other)
 |          Aligned objects.
 |
 |  all(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs)
 |      Return whether all elements are True, potentially over an axis.
 |
 |      Returns True unless there at least one element within a series or
 |      along a Dataframe axis that is False or equivalent (e.g. zero or
 |      empty).
 |
 |      Parameters
 |      ----------
 |      axis : {0 or 'index', 1 or 'columns', None}, default 0
 |          Indicate which axis or axes should be reduced.
 |
 |          * 0 / 'index' : reduce the index, return a Series whose index is the
 |            original column labels.
 |          * 1 / 'columns' : reduce the columns, return a Series whose index is the
 |            original index.
 |          * None : reduce all axes, return a scalar.
 |
 |      bool_only : bool, default None
 |          Include only boolean columns. If None, will attempt to use everything,
 |          then use only boolean data. Not implemented for Series.
 |      skipna : bool, default True
 |          Exclude NA/null values. If the entire row/column is NA and skipna is
 |          True, then the result will be True, as for an empty row/column.
 |          If skipna is False, then NA are treated as True, because these are not
 |          equal to zero.
 |      level : int or level name, default None
 |          If the axis is a MultiIndex (hierarchical), count along a
 |          particular level, collapsing into a scalar.
 |      **kwargs : any, default None
 |          Additional keywords have no effect but might be accepted for
 |          compatibility with NumPy.
 |
 |      Returns
 |      -------
 |      scalar or Series
 |          If level is specified, then, Series is returned; otherwise, scalar
 |          is returned.
 |
 |      See Also
 |      --------
 |      Series.all : Return True if all elements are True.
 |      DataFrame.any : Return True if one (or more) elements are True.
 |
 |      Examples
 |      --------
 |      **Series**
 |
 |      >>> pd.Series([True, True]).all()
 |      True
 |      >>> pd.Series([True, False]).all()
 |      False
 |      >>> pd.Series([]).all()
 |      True
 |      >>> pd.Series([np.nan]).all()
 |      True
 |      >>> pd.Series([np.nan]).all(skipna=False)
 |      True
 |
 |      **DataFrames**
 |
 |      Create a dataframe from a dictionary.
 |
 |      >>> df = pd.DataFrame({'col1': [True, True], 'col2': [True, False]})
 |      >>> df
 |         col1   col2
 |      0  True   True
 |      1  True  False
 |
 |      Default behaviour checks if column-wise values all return True.
 |
 |      >>> df.all()
 |      col1     True
 |      col2    False
 |      dtype: bool
 |
 |      Specify ``axis='columns'`` to check if row-wise values all return True.
 |
 |      >>> df.all(axis='columns')
 |      0     True
 |      1    False
 |      dtype: bool
 |
 |      Or ``axis=None`` for whether every value is True.
 |
 |      >>> df.all(axis=None)
 |      False
 |
 |  any(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs)
 |      Return whether any element is True, potentially over an axis.
 |
 |      Returns False unless there is at least one element within a series or
 |      along a Dataframe axis that is True or equivalent (e.g. non-zero or
 |      non-empty).
 |
 |      Parameters
 |      ----------
 |      axis : {0 or 'index', 1 or 'columns', None}, default 0
 |          Indicate which axis or axes should be reduced.
 |
 |          * 0 / 'index' : reduce the index, return a Series whose index is the
 |            original column labels.
 |          * 1 / 'columns' : reduce the columns, return a Series whose index is the
 |            original index.
 |          * None : reduce all axes, return a scalar.
 |
 |      bool_only : bool, default None
 |          Include only boolean columns. If None, will attempt to use everything,
 |          then use only boolean data. Not implemented for Series.
 |      skipna : bool, default True
 |          Exclude NA/null values. If the entire row/column is NA and skipna is
 |          True, then the result will be False, as for an empty row/column.
 |          If skipna is False, then NA are treated as True, because these are not
 |          equal to zero.
 |      level : int or level name, default None
 |          If the axis is a MultiIndex (hierarchical), count along a
 |          particular level, collapsing into a scalar.
 |      **kwargs : any, default None
 |          Additional keywords have no effect but might be accepted for
 |          compatibility with NumPy.
 |
 |      Returns
 |      -------
 |      scalar or Series
 |          If level is specified, then, Series is returned; otherwise, scalar
 |          is returned.
 |
 |      See Also
 |      --------
 |      numpy.any : Numpy version of this method.
 |      Series.any : Return whether any element is True.
 |      Series.all : Return whether all elements are True.
 |      DataFrame.any : Return whether any element is True over requested axis.
 |      DataFrame.all : Return whether all elements are True over requested axis.
 |
 |      Examples
 |      --------
 |      **Series**
 |
 |      For Series input, the output is a scalar indicating whether any element
 |      is True.
 |
 |      >>> pd.Series([False, False]).any()
 |      False
 |      >>> pd.Series([True, False]).any()
 |      True
 |      >>> pd.Series([]).any()
 |      False
 |      >>> pd.Series([np.nan]).any()
 |      False
 |      >>> pd.Series([np.nan]).any(skipna=False)
 |      True
 |
 |      **DataFrame**
 |
 |      Whether each column contains at least one True element (the default).
 |
 |      >>> df = pd.DataFrame({"A": [1, 2], "B": [0, 2], "C": [0, 0]})
 |      >>> df
 |         A  B  C
 |      0  1  0  0
 |      1  2  2  0
 |
 |      >>> df.any()
 |      A     True
 |      B     True
 |      C    False
 |      dtype: bool
 |
 |      Aggregating over the columns.
 |
 |      >>> df = pd.DataFrame({"A": [True, False], "B": [1, 2]})
 |      >>> df
 |             A  B
 |      0   True  1
 |      1  False  2
 |
 |      >>> df.any(axis='columns')
 |      0    True
 |      1    True
 |      dtype: bool
 |
 |      >>> df = pd.DataFrame({"A": [True, False], "B": [1, 0]})
 |      >>> df
 |             A  B
 |      0   True  1
 |      1  False  0
 |
 |      >>> df.any(axis='columns')
 |      0    True
 |      1    False
 |      dtype: bool
 |
 |      Aggregating over the entire DataFrame with ``axis=None``.
 |
 |      >>> df.any(axis=None)
 |      True
 |
 |      `any` for an empty DataFrame is an empty Series.
 |
 |      >>> pd.DataFrame([]).any()
 |      Series([], dtype: bool)
 |
 |  append(self, to_append, ignore_index=False, verify_integrity=False)
 |      Concatenate two or more Series.
 |
 |      Parameters
 |      ----------
 |      to_append : Series or list/tuple of Series
 |          Series to append with self.
 |      ignore_index : bool, default False
 |          If True, the resulting axis will be labeled 0, 1, …, n - 1.
 |      verify_integrity : bool, default False
 |          If True, raise Exception on creating index with duplicates.
 |
 |      Returns
 |      -------
 |      Series
 |          Concatenated Series.
 |
 |      See Also
 |      --------
 |      concat : General function to concatenate DataFrame or Series objects.
 |
 |      Notes
 |      -----
 |      Iteratively appending to a Series can be more computationally intensive
 |      than a single concatenate. A better solution is to append values to a
 |      list and then concatenate the list with the original Series all at
 |      once.
 |
 |      Examples
 |      --------
 |      >>> s1 = pd.Series([1, 2, 3])
 |      >>> s2 = pd.Series([4, 5, 6])
 |      >>> s3 = pd.Series([4, 5, 6], index=[3, 4, 5])
 |      >>> s1.append(s2)
 |      0    1
 |      1    2
 |      2    3
 |      0    4
 |      1    5
 |      2    6
 |      dtype: int64
 |
 |      >>> s1.append(s3)
 |      0    1
 |      1    2
 |      2    3
 |      3    4
 |      4    5
 |      5    6
 |      dtype: int64
 |
 |      With `ignore_index` set to True:
 |
 |      >>> s1.append(s2, ignore_index=True)
 |      0    1
 |      1    2
 |      2    3
 |      3    4
 |      4    5
 |      5    6
 |      dtype: int64
 |
 |      With `verify_integrity` set to True:
 |
 |      >>> s1.append(s2, verify_integrity=True)
 |      Traceback (most recent call last):
 |      ...
 |      ValueError: Indexes have overlapping values: [0, 1, 2]
 |
 |  apply(self, func, convert_dtype=True, args=(), **kwds)
 |      Invoke function on values of Series.
 |
 |      Can be ufunc (a NumPy function that applies to the entire Series)
 |      or a Python function that only works on single values.
 |
 |      Parameters
 |      ----------
 |      func : function
 |          Python function or NumPy ufunc to apply.
 |      convert_dtype : bool, default True
 |          Try to find better dtype for elementwise function results. If

In [69]:
d_data.head()

,customer_id,gender,senior_citizen,Partner,Dependents,tenure,phone_service,MultipleLines,InternetService,OnlineSecurity,...,number_of_received_message,minutes_of_call,num_of_call,internet_usage_megabytes,netflix_usage_megabytes,youtube_usage_megabytes,game_usage_megabytes,average_internet_ping,average_internet_speed_in_megabytes,total_usage_internet
0,9381-NDKME,Female,1,Yes,No,24,No,No phone service,DSL,No,...,34.0,126.0,14.0,2629.0,976.0,599.0,8.0,15.0,20.425580,4204.0
1,3831-YCPUO,Female,0,Yes,Yes,72,Yes,No,Fiber optic,Yes,...,95.0,70.0,42.0,37258.0,7090.0,5330.0,6664.0,15.0,21.759168,49678.0
2,1506-YJTYT,Male,0,Yes,Yes,45,Yes,Yes,DSL,Yes,...,79.0,168.0,22.0,19331.0,7069.0,6596.0,761.0,15.0,22.123215,32996.0
3,2272-UOINI,Female,0,No,No,7,Yes,No,DSL,Yes,...,89.0,166.0,28.0,16221.0,8202.0,6167.0,608.0,15.0,22.169331,30590.0
4,1641-BYBTK,Male,0,No,Yes,6,Yes,No,Wireless,No internet service,...,70.0,132.0,22.0,17526.0,9309.0,8484.0,613.0,15.0,22.263776,35319.0

### String Operation

start from this submenu for string operation
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.capitalize.html

lowercase customer_id using `str.lower()`

In [73]:
# YOUR CODE
d_data.customer_id = d_data.customer_id.str.lower()

In [74]:
d_data

,customer_id,gender,senior_citizen,Partner,Dependents,tenure,phone_service,MultipleLines,InternetService,OnlineSecurity,...,number_of_received_message,minutes_of_call,num_of_call,internet_usage_megabytes,netflix_usage_megabytes,youtube_usage_megabytes,game_usage_megabytes,average_internet_ping,average_internet_speed_in_megabytes,total_usage_internet
0,9381-ndkme,Female,1,Yes,No,24,No,No phone service,DSL,No,...,34.0,126.0,14.0,2629.0,976.0,599.0,8.0,15.0,20.425580,4204.0
1,3831-ycpuo,Female,0,Yes,Yes,72,Yes,No,Fiber optic,Yes,...,95.0,70.0,42.0,37258.0,7090.0,5330.0,6664.0,15.0,21.759168,49678.0
2,1506-yjtyt,Male,0,Yes,Yes,45,Yes,Yes,DSL,Yes,...,79.0,168.0,22.0,19331.0,7069.0,6596.0,761.0,15.0,22.123215,32996.0
3,2272-uoini,Female,0,No,No,7,Yes,No,DSL,Yes,...,89.0,166.0,28.0,16221.0,8202.0,6167.0,608.0,15.0,22.169331,30590.0
4,1641-bybtk,Male,0,No,Yes,6,Yes,No,Wireless,No internet service,...,70.0,132.0,22.0,17526.0,9309.0,8484.0,613.0,15.0,22.263776,35319.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,8779-qrdmv,Male,1,No,No,1,No,No phone service,DSL,No,...,38.0,244.0,12.0,3046.0,937.0,777.0,8.0,299.0,6.436184,4760.0
5982,7663-ztegj,Male,0,No,Yes,29,Yes,Yes,Fiber optic,No,...,74.0,130.0,20.0,15494.0,7110.0,9321.0,583.0,299.0,6.527040,31925.0
5983,4238-jsswh,Female,1,Yes,No,35,Yes,Yes,Fiber optic,No,...,25.0,122.0,14.0,9380.0,897.0,969.0,6.0,299.0,6.782600,11246.0
5984,2740-jfbok,Male,0,No,No,10,Yes,Yes,Wireless,No internet service,...,177.0,53.0,33.0,45238.0,7397.0,6438.0,2132.0,299.0,7.825139,59073.0
5985,0835-jkadz,Female,0,No,No,71,Yes,Yes,Fiber optic,No,...,70.0,141.0,26.0,19075.0,7667.0,6710.0,714.0,299.0,7.917201,33452.0

### Save the dataframe to csv

In [75]:
d_data.to_csv("telcom_user_extended_day4.csv", index=False)

### Exercise

1. drop column `InstallApp`
2. pop column `Churn` and assign to `target` variable
3. replace `Credit card (automatic)` in PaymentMethod to `Credit card`
4. `minutes of call` divided by `num_of_call` and assign to `average_call_duration`

In [76]:
d_data.columns

Index(['customer_id', 'gender', 'senior_citizen', 'Partner', 'Dependents',
       'tenure', 'phone_service', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'InstallApp', 'email', 'kodepos', 'RecordedDate', 'age',
       'number_of_send_message', 'number_of_received_message',
       'minutes_of_call', 'num_of_call', 'internet_usage_megabytes',
       'netflix_usage_megabytes', 'youtube_usage_megabytes',
       'game_usage_megabytes', 'average_internet_ping',
       'average_internet_speed_in_megabytes', 'total_usage_internet'],
      dtype='object')

In [77]:
target = d_data.pop("Churn")

In [78]:
target

0       Yes
1        No
2        No
3        No
4        No
       ...
5981    Yes
5982     No
5983     No
5984     No
5985     No
Name: Churn, Length: 5986, dtype: object

In [81]:
"Churn" in d_data.columns

False

In [82]:
d_data["average_call_duration"] = d_data.minutes_of_call / d_data.num_of_call

In [83]:
d_data

,customer_id,gender,senior_citizen,Partner,Dependents,tenure,phone_service,MultipleLines,InternetService,OnlineSecurity,...,minutes_of_call,num_of_call,internet_usage_megabytes,netflix_usage_megabytes,youtube_usage_megabytes,game_usage_megabytes,average_internet_ping,average_internet_speed_in_megabytes,total_usage_internet,average_call_duration
0,9381-ndkme,Female,1,Yes,No,24,No,No phone service,DSL,No,...,126.0,14.0,2629.0,976.0,599.0,8.0,15.0,20.425580,4204.0,9.000000
1,3831-ycpuo,Female,0,Yes,Yes,72,Yes,No,Fiber optic,Yes,...,70.0,42.0,37258.0,7090.0,5330.0,6664.0,15.0,21.759168,49678.0,1.666667
2,1506-yjtyt,Male,0,Yes,Yes,45,Yes,Yes,DSL,Yes,...,168.0,22.0,19331.0,7069.0,6596.0,761.0,15.0,22.123215,32996.0,7.636364
3,2272-uoini,Female,0,No,No,7,Yes,No,DSL,Yes,...,166.0,28.0,16221.0,8202.0,6167.0,608.0,15.0,22.169331,30590.0,5.928571
4,1641-bybtk,Male,0,No,Yes,6,Yes,No,Wireless,No internet service,...,132.0,22.0,17526.0,9309.0,8484.0,613.0,15.0,22.263776,35319.0,6.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,8779-qrdmv,Male,1,No,No,1,No,No phone service,DSL,No,...,244.0,12.0,3046.0,937.0,777.0,8.0,299.0,6.436184,4760.0,20.333333
5982,7663-ztegj,Male,0,No,Yes,29,Yes,Yes,Fiber optic,No,...,130.0,20.0,15494.0,7110.0,9321.0,583.0,299.0,6.527040,31925.0,6.500000
5983,4238-jsswh,Female,1,Yes,No,35,Yes,Yes,Fiber optic,No,...,122.0,14.0,9380.0,897.0,969.0,6.0,299.0,6.782600,11246.0,8.714286
5984,2740-jfbok,Male,0,No,No,10,Yes,Yes,Wireless,No internet service,...,53.0,33.0,45238.0,7397.0,6438.0,2132.0,299.0,7.825139,59073.0,1.606061
5985,0835-jkadz,Female,0,No,No,71,Yes,Yes,Fiber optic,No,...,141.0,26.0,19075.0,7667.0,6710.0,714.0,299.0,7.917201,33452.0,5.423077